name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Run Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          args: "--codes --no-color -q"
          annotate: warning

      - name: Setup Python
        uses: actions/setup-python@v1

      - name: Validate Locales
        run: python scripts/validate_locales.py
