name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1

      - name: Find Unused Locales
        run: python scripts/find_unused_locales.py

      - name: Run Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          args: "--codes --no-color -q"
          annotate: warning
