name: Localization

on:
  push:
    branches:
      - master

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - run: pip install requests

      - name: Find Unused Locales
        run: python scripts/find_unused_locales.py

      - name: Upload to CurseForge
        run: python scripts/upload_locales.py
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
