name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Release Classic
        run: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -g 1.13.5
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_OAUTH }}
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}

      - name: Release Retail
        run: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_OAUTH }}
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
