name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Classic
        run: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -g 1.13.5
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_OAUTH }}

      - name: Retail
        run: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_OAUTH }}
