name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Run Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          args: "--codes --no-color -q"
          annotate: warning

      - name: Setup Python
        uses: actions/setup-python@v1

      - name: Install requests
        run: pip install requests

      - name: Validate Locales
        run: python scripts/validate_locales.py

      - name: Upload Locales
        run: python scripts/upload_locales.py
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}

      - name: Release Classic
        run: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -g 1.13.5
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_OAUTH }}
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}

      - name: Release Retail
        run: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_OAUTH }}
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
