name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Run Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          args: "--codes --no-color -q"
          annotate: warning

      - name: Setup Python
        uses: actions/setup-python@v1

      - name: Install requests
        run: pip install requests

      - name: Validate Locales
        run: python scripts/validate_locales.py

      - name: Upload Locales
        run: python scripts/upload_locales.py
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}

      - name: Release Classic
        uses: BigWigsMods/packager@master
        with:
          args: -g classic
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}

      - name: Release Retail
        uses: BigWigsMods/packager@master
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
